<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="format-detection" content="telephone=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="author" content="">
	<meta name="keywords" content="">
	<meta name="description" content="">

	<!--
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        -->
        <link rel="stylesheet" type="text/css" href="assets/StyleLivres.css">
        <link rel="stylesheet" type="text/css" href="assets/StyleFormLivres.css">
	<link rel="stylesheet" type="text/css" href="assets/normalize.css">
	<link rel="stylesheet" type="text/css" href="assets/icomoon/icomoon.css">
	<link rel="stylesheet" type="text/css" href="assets/vendor.css">
	<link rel="stylesheet" type="text/css" href="assets/style2.css">
    <link rel="stylesheet" type="text/css" href="assets/CarteAdherent">
    <link rel="stylesheet" type="text/css" href="assets/StyleDetailsADR">      
    
    <link rel="stylesheet" href="../../assets/bootstrap-icons-1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


    <title><?= $page_title ?></title>


    <link rel="stylesheet" <?php if (empty($template)): ?> href="./assets/style.css" <?php else: ?>
            href="./assets/style2.css" <?php endif ?>>
 
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    
    <style>

    </style>
</head>
<?php if($template!="signup" && $template!="login" && $template!="logout" && $template!="LivreDetails"&& $template!="forgetpass"&&$template!="resetpass"):?>
<body data-bs-spy="scroll" data-bs-target="#header" tabindex="0">
<div id="header-wrap">

<div class="top-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="social-links">
                    <ul>
                        <li>
                            <a href="#"><i class="icon icon-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="icon icon-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="icon icon-youtube-play"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="icon icon-behance-square"></i></a>
                        </li>
                    </ul>
                </div><!--social-links-->
            </div>
            <div class="col-md-6">
                <div class="right-element">
                <?php if (session_status() != PHP_SESSION_NONE && array_key_exists('iduser', $_SESSION)): ?>
                    <a href="./logout.php">
                        <button class="btn btn-outline-secondary">logout</button>
                    </a>
                    <?php else: ?>
                             <a href="./login/">
                                 <button class="btn btn-outline-secondary">Login</button>
                                </a>
                                <a href="./signup/" class="mx-2">
                                    <button class="btn btn-outline-secondary">SignUp</button>
                                 </a>
                     <?php endif; ?>








                    <a href="#" class="user-account for-buy"><i
                            class="icon icon-user"></i><span>Account</span></a>
                    <a href="#" class="cart for-buy"><i class="icon icon-clipboard"></i><span>Cart:(0
                            $)</span></a>

                    <div class="action-menu">

                        <div class="search-bar">
                            <a href="#" class="search-button search-toggle" data-selector="#header-wrap">
                                <i class="icon icon-search"></i>
                            </a>
                            <form role="search" method="get" class="search-box">
                                <input class="search-field text search-input" placeholder="Search"
                                    type="search">
                            </form>
                        </div>
                    </div>

                </div><!--top-right-->
            </div>

        </div>
    </div>
</div><!--top-content-->

<header id="header">
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-2">
                <div class="main-logo">
                    <a href="index.html"><img src="assets/images/main-logo.png" alt="logo"></a>
                </div>

            </div>

            <div class="col-md-10">

                <nav id="navbar">
                    <div class="main-menu stellarnav">
                        <ul class="menu-list">
                            <li class="menu-item active"><a href="index.php">Home</a></li>
                                        <ul>
                                    <li class="active"><a href="index.php"> Home </a></li>
                                    <li><a href="index.html">About</a></li>
                                    <li><a href="index.html">Styles</a></li>
                                    <li><a href="index.html">Blog</a></li>
                                    <li><a href="index.html">Post Single</a></li>
                                    <li><a href="index.html">Our Store</a></li>
                                    <li><a href="index.html">Product Single</a></li>
                                    <li><a href="index.html">Contact</a></li>
                                    <li><a href="index.html">Thank You</a></li>
                                </ul>

                            </li>
                           
                            <li class="menu-item"> <a href="<?php 
                                if (isset($_SESSION['email']) && $_SESSION['email'] === 'admin@gmail.com') {
                                      echo 'ListeLivre_A.php';
                                        } elseif (isset($_SESSION['email'])) {
                                      echo 'ListeLivre_CLT.php';
                                 } else {
                                         echo '#';
                                        }
                                  ?>" class="nav-link">
                                 BOOKS </a>
                            </li>
                            
                            <li class="menu-item"><a href="#popular-books" class="nav-link">Popular</a></li>
                            <li class="menu-item"><a href="#special-offer" class="nav-link">Offer</a></li>
                            <li class="menu-item"><a href="#latest-blog" class="nav-link">Articles</a></li>
                            <li class="menu-item"><a href="#download-app" class="nav-link">Download App</a></li>
                        </ul>

                        <div class="hamburger">
                            <span class="bar"></span>
                            <span class="bar"></span>
                            <span class="bar"></span>
                        </div>

                    </div>
                </nav>

            </div>

        </div>
    </div>
</header>

</div><!--header-wrap-->
<?php endif ?>


    <div class="preloader">
        <div class="content-preloader">
            <?php if (empty($template)): ?>
                <img src="./assets/images/livre.jpg" alt="library">
            <?php else: ?>

            <?php endif ?>

        </div>
    </div>
    <nav class="navbar fixed-top">
        <div class="container">
            <?php if (empty($template)): ?>
                <a href="./index.php">
                <img src="./assets/images/livre.jpg" class="logo" alt="library">
                </a>
            <?php else: ?>
                <a href="../index.php">
              
                </a>
            <?php endif ?>
            <!--
            <?php //if (session_status() != PHP_SESSION_NONE && array_key_exists('iduser', $_SESSION)): ?>
                <a href="./logout.php">
                    <button class="btn btn-outline-secondary">logout</button>
                </a>
            <?php //else: ?>
                <div class="d-flex">
                    <a href="./login/">
                        <button class="btn btn-outline-secondary">Login</button>
                    </a>
                    <a href="./signup/" class="mx-2">
                        <button class="btn btn-outline-secondary">SignUp</button>
                    </a>

                </div>
            <?php//endif; ?>
            -->
        </div>
    </nav>
    <?php if (empty($template) && !$show): ?>

        <div>

            <div class="section">
                <div class="text">
                    
                    <a href="./ListCategory/">
                        <button class="btn btn-dark">
                            Browse livres
                        </button>
                    </a>
                </div>
            </div>
            <div class="container">
                <footer class="d-flex flex-wrap justify-content-between align-items-center my-4 border-top">
                    <div class="col-md-12 d-flex  justify-content-center align-items-center">
                        <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 library, Inc</span>
                    </div>
                </footer>
            </div>
        </div>
    <?php else: ?>
        <?php include $template.".phtml" ?>
    <?php endif; ?>
</body>

<script <?php if (empty($template)): ?> src="./assets/main.js" <?php else: ?> <?php endif; ?>></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

    <script src="assets/js/jquery-1.11.0.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
		crossorigin="anonymous"></script>

	<script src="assets/js/plugins.js"></script>
	<script src="assets/js/script.js"></script>



</html>